png("uniqwords.png", width=400, height=400)
x<-read.csv("uniqwords.csv",header=T)
h=hist(x$word.count, cex.lab=1.5, cex.main=2, main="Unique Words Per Document", xlab="Number of Unique Words", breaks=100)
dev.off()
 
png("uniqwords-boxplot.png", width=400, height=400)
x<-read.csv("uniqwords.csv",header=T)
b=boxplot(x$word.count, cex.lab=1.5, cex.main=2, main="Unique Words Per Document", xlab="Number of Unique Words", breaks=100)
dev.off()
 
png("uniq-lessoutliers.png", width=400, height=400)
x<-read.csv("uniqwords-lessoutliers.csv",header=T)
h=hist(x$word.count, cex.lab=1.5, cex.main=2, main="Unique Words Less Outliers\nPer Document", xlab="Number of Unique Words", breaks=100)
dev.off()
q()
