png("class_count.png")
x<-read.csv("../SPAMTrain.label.4327",header=F, sep=' ')
y<-table(x$V1)
l<-paste(c("Spam","Ham"), c("(", "("), y, c(")", ")"))
h=pie(y, labels=l, main="E-Mail Corpus Class Counts")
dev.off()
#q()
